#!/bin/sh
cd "$(dirname "$0")"
if [ -f /EON ]; then
  export LD_LIBRARY_PATH="/system/lib64:../../../third_party/mapbox-gl-native-qt/aarch64:$LD_LIBRARY_PATH"
fi
export QT_PLUGIN_PATH="../../../third_party/qt-plugins/$(uname -m)"
exec ./_navd
